<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260801225938 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phase VARCHAR(255) NOT NULL, round INT NOT NULL, slot INT NOT NULL, sort_order INT NOT NULL, score_home INT DEFAULT NULL, score_away INT DEFAULT NULL, status VARCHAR(255) NOT NULL, next_match_id INT DEFAULT NULL, next_match_is_home BOOLEAN DEFAULT NULL, loser_next_match_id INT DEFAULT NULL, loser_next_match_is_home BOOLEAN DEFAULT NULL, tournament_id INT NOT NULL, group_id INT DEFAULT NULL, home_team_id INT DEFAULT NULL, away_team_id INT DEFAULT NULL, winner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4868BC8A33D1A3E7 ON game_match (tournament_id)');
        $this->addSql('CREATE INDEX IDX_4868BC8AFE54D947 ON game_match (group_id)');
        $this->addSql('CREATE INDEX IDX_4868BC8A9C4C13F6 ON game_match (home_team_id)');
        $this->addSql('CREATE INDEX IDX_4868BC8A45185D02 ON game_match (away_team_id)');
        $this->addSql('CREATE INDEX IDX_4868BC8A5DFCD4B8 ON game_match (winner_id)');
        $this->addSql('CREATE TABLE group_standing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, played INT NOT NULL, wins INT NOT NULL, losses INT NOT NULL, points INT NOT NULL, score_for INT NOT NULL, score_against INT NOT NULL, group_id INT NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68AAC6A7FE54D947 ON group_standing (group_id)');
        $this->addSql('CREATE INDEX IDX_68AAC6A7296CD8AE ON group_standing (team_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, wins INT NOT NULL, losses INT NOT NULL, tournaments_played INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, seed INT NOT NULL, tournament_id INT NOT NULL, player1_id INT NOT NULL, player2_id INT DEFAULT NULL, group_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4E0A61F33D1A3E7 ON team (tournament_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61FC0990423 ON team (player1_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61FD22CABCD ON team (player2_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61FFE54D947 ON team (group_id)');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, has_group_stage BOOLEAN NOT NULL, bracket_type VARCHAR(255) NOT NULL, team_mode VARCHAR(255) NOT NULL, group_count INT NOT NULL, qualifiers_per_group INT NOT NULL, status VARCHAR(255) NOT NULL, current_match_id INT DEFAULT NULL, next_match_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tournament_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(40) NOT NULL, tournament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC96D4DC33D1A3E7 ON tournament_group (tournament_id)');
        $this->addSql('ALTER TABLE game_match ADD CONSTRAINT FK_4868BC8A33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_match ADD CONSTRAINT FK_4868BC8AFE54D947 FOREIGN KEY (group_id) REFERENCES tournament_group (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_match ADD CONSTRAINT FK_4868BC8A9C4C13F6 FOREIGN KEY (home_team_id) REFERENCES team (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_match ADD CONSTRAINT FK_4868BC8A45185D02 FOREIGN KEY (away_team_id) REFERENCES team (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_match ADD CONSTRAINT FK_4868BC8A5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES team (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE group_standing ADD CONSTRAINT FK_68AAC6A7FE54D947 FOREIGN KEY (group_id) REFERENCES tournament_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE group_standing ADD CONSTRAINT FK_68AAC6A7296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FC0990423 FOREIGN KEY (player1_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FD22CABCD FOREIGN KEY (player2_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FFE54D947 FOREIGN KEY (group_id) REFERENCES tournament_group (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_group ADD CONSTRAINT FK_AC96D4DC33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_match DROP CONSTRAINT FK_4868BC8A33D1A3E7');
        $this->addSql('ALTER TABLE game_match DROP CONSTRAINT FK_4868BC8AFE54D947');
        $this->addSql('ALTER TABLE game_match DROP CONSTRAINT FK_4868BC8A9C4C13F6');
        $this->addSql('ALTER TABLE game_match DROP CONSTRAINT FK_4868BC8A45185D02');
        $this->addSql('ALTER TABLE game_match DROP CONSTRAINT FK_4868BC8A5DFCD4B8');
        $this->addSql('ALTER TABLE group_standing DROP CONSTRAINT FK_68AAC6A7FE54D947');
        $this->addSql('ALTER TABLE group_standing DROP CONSTRAINT FK_68AAC6A7296CD8AE');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61F33D1A3E7');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61FC0990423');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61FD22CABCD');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61FFE54D947');
        $this->addSql('ALTER TABLE tournament_group DROP CONSTRAINT FK_AC96D4DC33D1A3E7');
        $this->addSql('DROP TABLE game_match');
        $this->addSql('DROP TABLE group_standing');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE tournament_group');
    }
}
